/* Exploratory Data Analysis Project (EDA)
=================================================================================
Purpose:
      To create queries that can help explore and understand the database before
      performing any kind of operations on it.
---------------------------------------------------------------------------------
Highlights:
        In this we explore the Dimensions and Measures of the database
        - Dimensions -> Non numeric data that gives some descriptive information
                        about table/database
                        ex- customer name, date of birth etc.
        - Measures -> Numeric and aggregate-able data that gives metrics of the
                      table/database
--------------------------------------------------------------------------------
================================================================================ */

/*========================================================================== */
-- Exploring all Objects in Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Exploring all Columns in Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'fact_sales';

/*========================================================================== */
-- Exploring Dimensions
-- 1. Exploring country from dim_customers
SELECT DISTINCT country FROM gold.dim_customers;

-- 2. Exploring categories from dim_products
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3;

/*========================================================================== */
-- Date Exploration
-- 1. Find the total years of order
SELECT
	MIN(order_date) AS first_year,
	MAX(order_date) AS last_year,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS total_order_years
FROM gold.fact_sales

-- 2. Find the youngest customer
SELECT
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_customer_age,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_customer_age
FROM gold.dim_customers;

/*========================================================================== */
-- Measures Exploration
-- Calculating the key metrics of business (Big numbers). Highest level of Aggregation | Lowest level of details

-- 1. Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- 2. Find how many items are sold
SELECT SUM(quantity) AS total_items_sold FROM gold.fact_sales


-- 3. Find the average selling price
SELECT AVG(price) AS average_selling_price FROM gold.fact_sales

-- 4. Find the Total number of orders
SELECT COUNT(order_number) AS total_orders_count FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders_count FROM gold.fact_sales

-- 5. Find the Total number of products
SELECT COUNT(product_id) AS total_product_count FROM gold.dim_products

-- 6. Find the Total number of customers
SELECT COUNT(DISTINCT customer_id) AS total_customers_count FROM gold.dim_customers

-- 7. Find the Total number of customers that have placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customer_with_order FROM gold.fact_sales

/*========================================================================== */
-- Generating report of the Measures
SELECT 'total_sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'total_items_sold', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'average_selling_price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'total_orders_count', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'total_product_count', COUNT(product_id) FROM gold.dim_products
UNION ALL
SELECT 'total_customers_count', COUNT(DISTINCT customer_id) FROM gold.dim_customers
UNION ALL
SELECT 'total_customer_with_order', COUNT(DISTINCT customer_key) FROM gold.fact_sales

/*========================================================================== */
-- Magnitude Analysis
-- Compare the measures by different categories of dimensions
-- 1. Find total customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers_per_country 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers_per_country DESC

-- 2. Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers_per_gender
FROM gold.dim_customers
GROUP BY gender

-- 3. Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products_per_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_products_per_category DESC

-- 4. What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_cost_per_category
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost_per_category DESC

-- 5. What is the total revenue generated by each category?
SELECT
	gprd.category,
	SUM(fsal.sales_amount) AS total_revenue_per_category
FROM gold.fact_sales AS fsal
LEFT JOIN gold.dim_products AS gprd
ON fsal.product_key = gprd.product_key
GROUP BY gprd.category
ORDER BY total_revenue_per_category DESC

-- 6. Find total revenue generated by each customer
SELECT
	dcus.customer_key,
	dcus.first_name,
	dcus.last_name,
	SUM(fsal.sales_amount) AS total_revenue_per_customer
FROM gold.fact_sales AS fsal
LEFT JOIN gold.dim_customers AS dcus
ON fsal.customer_key = dcus.customer_key
GROUP BY dcus.customer_key, dcus.first_name, dcus.last_name
ORDER BY total_revenue_per_customer DESC /* this is High Cardinal Analysis as the number of columns and rows are high */

-- 7. What is the distribution of sold items across countries?
SELECT
	dc.country,
	COUNT(fs.quantity) AS items_sold_per_country
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY items_sold_per_country DESC /* this is Low Cardinal Analysis as the number of columns and rows are less */

/*========================================================================== */
-- Ranking Analysis
-- Ranking the dimension by measures to find N highest/lowest

-- 1. Which 5 products generate the highest revenue?
SELECT TOP 5
	dp.product_name,
	SUM(fs.sales_amount) AS total_sales
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_sales DESC

-- With Window Function
SELECT
	*
FROM (SELECT
	dp.product_name,
	SUM(fs.sales_amount) AS total_sales,
	ROW_NUMBER() OVER(ORDER BY SUM(fs.sales_amount) DESC) AS flag_rank
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name) t
WHERE flag_rank <= 5

-- 2. What are the 5 worst-performing products in terms of total sales?
SELECT TOP 5
	dp.product_name,
	SUM(fs.sales_amount) AS total_sales
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_sales

-- With Window Function
SELECT
	*
FROM (SELECT
	dp.product_name,
	SUM(fs.sales_amount) AS total_sales,
	ROW_NUMBER() OVER(ORDER BY SUM(fs.sales_amount) ASC) AS flag_rank
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name)t
WHERE flag_rank <= 5

-- 3. Find the top 10 customers with the highest revenue
SELECT TOP 10
	dc.customer_id,
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) AS total_sales
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_id, dc.first_name, dc.last_name
ORDER BY total_sales DESC

-- 4. Find 3 customers with the fewest orders places
SELECT TOP 3
	dc.customer_id,
	dc.first_name,
	dc.last_name,
	COUNT(DISTINCT fs.order_number) AS total_orders
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_id, dc.first_name, dc.last_name
ORDER BY total_orders
